## Deep Learning for Computer Vision with Python

# Chapter 8. Parameterized Learning

In the task of machine learning, parameterization involves defining a problem in
terms of four key components: 

（1）data, 

（2）a scoring function, 

（3）a loss function, 

（4）weights and biases.


A Simple Linear Classifier With Python

In [1]:
import numpy as np

In [2]:
import cv2

In [3]:
labels = ["dog", "cat", "panda"]
np.random.seed(1)

In [4]:
W = np.random.randn(3, 3072)  #32*32*3
b = np.random.randn(3)

In [5]:
W

array([[ 1.62434536, -0.61175641, -0.52817175, ...,  1.20731703,
         1.37766662,  0.63628393],
       [ 0.05529735,  0.40581712,  1.24845728, ..., -1.95176055,
         0.21272915,  0.10822446],
       [ 0.13130697, -1.36381382,  0.23921477, ..., -0.67836182,
        -1.13521117,  0.05031758]])

In [6]:
b

array([-0.72996827, -0.37260481,  0.9461125 ])

In [7]:
orig = cv2.imread("beagle.png")

In [8]:
orig.shape

(250, 424, 3)

In [9]:
image = cv2.resize(orig, (32, 32)).flatten() #32*32*3=3072

In [10]:
32*32*3

3072

In [11]:
image.shape

(3072,)

In [12]:
scores = W.dot(image) + b

In [13]:
scores

array([8565.58574885,  219.99431827, 6318.29515515])

In [17]:
scores[2]=12000

In [19]:
scores

array([ 8565.58574885,   219.99431827, 12000.        ])

In [20]:
for (label, score) in zip(labels, scores):
    print("[INFO] {}: {:.2f}".format(label, score))

[INFO] dog: 8565.59
[INFO] cat: 219.99
[INFO] panda: 12000.00


In [21]:
x=cv2.putText(orig, "Label: {}".format(labels[np.argmax(scores)]),
            (10, 30), cv2.FONT_HERSHEY_SIMPLEX, 0.9, (0, 255, 0), 2)

In [22]:
cv2.imshow("Image", orig)
cv2.waitKey(0)

-1